# Generated by Django 2.2.4 on 2019-08-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190821_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCategory',
        ),
    ]
