# Generated by Django 2.2.4 on 2019-08-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_imagecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Mens Jeans', 'Mens Jeans'), ('Mens Tshirt', 'Mens Tshirt'), ('Mens Watch', 'Mens Watch'), ('WoMens Jeans', 'WoMens Jeans'), ('WoMens Tshirt', 'WoMens Tshirt'), ('WoMens Watch', 'WoMens Watch'), ('WoMens Parse', 'WoMens Parse')], max_length=120),
        ),
    ]
